export const FETCH_WHISKEYS = "FETCH_WHISKEYS"
export const FETCH_WHISKEY = "FETCH_WHISKEY"
export const CHANGE_WHISKEY_RATING = "CHANGE_WHISKEY_RATING"
export const FETCH_RATING_TYPES = "FETCH_RATING_TYPES"
